services:
  - type: web
    name: bjp-localbody-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://bjp-mebership.vercel.app
      - key: VOTER_DB_URI
        sync: false
      - key: APP_DB_URI
        sync: false
      - key: MONGO_APP_URL
        sync: false
      - key: WARD_DB_URI
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: ADMIN_SESSION_SECRET
        sync: false
      - key: B2_APPLICATION_KEY_ID
        sync: false
      - key: B2_KEY_ID
        sync: false
      - key: B2_APPLICATION_KEY
        sync: false
      - key: B2_APP_KEY
        sync: false
      - key: B2_BUCKET_NAME
        value: bjp-localbody-media
      - key: B2_ENDPOINT
        value: s3.us-east-005.backblazeb2.com
      - key: SMS_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
